### ISSUE TITLE
install fail due to wrong lock file path

### ISSUE THREAD

**Issue by dzebrys** [wbartels/IPSet_ASUS_Lite#3]
hi,

FYI, trying to install v3.6.7 on asus rt-ac86u release 386.2_2

@rt-ac86u root]$ uname -a
Linux rt-ac86u 4.1.27 #2 SMP PREEMPT Tue Apr 13 17:53:19 EDT 2021 aarch64 ASUSWRT-Merlin

with fallowing glitch:

@rt-ac86u scripts]$ curl https://raw.githubusercontent.com/wbartels/IPSet_ASUS_Lite/master/firewall.sh --output /jffs/scripts/firewall && chmo
d 755 /jffs/scripts/firewall && /jffs/scripts/firewall
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 32700  100 32700    0     0   105k      0 --:--:-- --:--:-- --:--:--  107k
/jffs/scripts/firewall: line 696: can't create /tmp/var/lock/skynet.lock: **nonexistent directory**

seems that latest merlin uses another locker location:

@rt-ac86u root]$ ff *.lock
/var/nvram.lock
/var/lock/cfg_mnt.lock
/var/lock/cron.lock
/var/lock/bwdpi_sqlite.lock
/var/lock/amas_node_list.lock
/var/lock/nmpvc.lock
/var/lock/wlcevent.lock
/var/lock/conn_diag.lock
/var/lock/usbnas.lock
/var/lock/roaming.lock
/var/lock/tg_roaming.lock
/var/lock/onboarding.lock
/var/lock/clientlist.lock
/var/lock/allwevent.lock
/var/lock/wiredclientlist.lock
/var/lock/sda.lock
/var/lock/sda1.lock
/var/lock/sda2.lock
/var/lock/sg0.lock
/var/lock/printer.lock
/var/lock/usb.lock
/var/lock/mt_routes.lock
/var/lock/resolv.lock
/var/lock/firewall.lock
/var/lock/mcpd.lock
/var/lock/nt_db.lock
/var/lock/networkmap.lock
/var/lock/httpd.lock
/var/lock/tg_bsd_diag.lock
/var/lock/3-1:1.0.lock
/var/lock/3-1.lock
/var/lock/cfez_buf.lock

br/Piotr

**Comment by wbartels** [comment]
Thanks for the info!

What is the output from the following command on your rt-ac86u?
`ls /var -all`
I get this:
`lrwxrwxrwx    1 username root             7 Apr  2 05:20 /var -> tmp/var`

I asume that when you change the line from:
`lockfile="/tmp/var/lock/skynet.lock"`
To:
`lockfile="/var/lock/skynet.lock"`
That it fixes the problem.
On my RT-AC68U it still works, because "/var/lock/skynet.lock" is a symlink to "/tmp/var/lock/skynet.lock"

**Comment by wbartels** [comment]
Version v3.6.8 should fix the install problem.
