### ISSUE TITLE
SkyNet starts/installs twice?!

### ISSUE THREAD

**Issue by iJorgen** [wbartels/IPSet_ASUS_Lite#5]
Hi!
I noticed SkyNet always starts/installs two times after each reboot. Not a big thing since it works, but maybe a small bug?! Noticed some time-out values had changed in the latest release that might be a clue?!

Nov 17 09:56:26 skynet: [i] Install
Nov 17 09:56:27 skynet: [i] Update blocklist_ip
Nov 17 09:56:27 skynet: [i] Update blocklist_domain
...

Nov 17 09:56:37 skynet: [i] Install
Nov 17 09:56:37 skynet: [i] Update passlist
Nov 17 09:56:38 skynet: [i] Update blocklist_ip
...

**Comment by wbartels** [comment]
Hello iJorgen,

With my router I can't reproduce the double installation after reboot.
Can you send me a logfile with double installation to bonsai.ank_0y@icloud.com ?
(This is a temporarily email address)

Thanks! Willem

**Comment by wbartels** [comment]
iJorgan, thanks for sending the logfile!

**Comment by wbartels** [comment]
Best wishes for 2023!
Still I can't reproduce the double installation.

The only way I found is to do something like:
`skynet && skynet reset`

Or run something like this direct after reboot:
`/jffs/scripts/firewall reset`

It is difficult to fix a bug I can't reproduce.
Can you describe how I can reproduce the double installation form the latest GitHub source?

Thanks,
Willem

**Comment by iJorgen** [comment]
Wish you the same!!

Seems it's only happening on my setup and not a major issue that SkyNet starts twice, so I can live with it... :-)
